name: Build and Deploy (Jigsaw + Tailwind)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          composer install --no-dev --prefer-dist --no-progress --no-interaction
          npm ci

      - name: Build CSS
        run: npm run build:css

      - name: Build site
        run: vendor/bin/jigsaw build production

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build_production
          publish_branch: gh-pages
