name: Build and Deploy (Jigsaw + Tailwind → docs)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer
          extensions: mbstring, dom, fileinfo, tokenizer, ctype, json

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Composer deps
        run: composer install --no-dev --prefer-dist --no-progress --no-interaction

      - name: Install Node deps
        run: npm install --no-audit --no-fund

      - name: Build Tailwind CSS
        run: npx tailwindcss -i source/_assets/css/tailwind.css -o source/assets/css/main.css --minify

      - name: Build site with Jigsaw
        run: php vendor/bin/jigsaw build production

      - name: Disable Jekyll (safety)
        run: touch build_production/.nojekyll

      - name: Deploy built site to main/docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main # stay on main
          folder: build_production # what to publish
          target-folder: docs # where to publish
          clean: true
